# workflow triggers
on:
  push:
    branches: [main]
  workflow_dispatch:

  # Allows external webhook trigger
  repository_dispatch:
    types: [ publish_blog ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1

      -run: |
        echo "test"
