# workflow triggers
on:
  repository_dispatch:
    types: [ publish_blog ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.1
      - name: build
        working-directory: sdi-app
        run: npm ci
