# workflow triggers
on:
  push:
    tags: ['store-front.*']
    branches: [main]
  repository_dispatch:
    types: [ publish_blog ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.1
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Build
        working-directory: ./sdi-app/
        run: |
          cat << EOF > .env
          STRAPI_API_URL=${{ secrets.STRAPI_API_URL }}
          STRAPI_TOKEN=${{ secrets.STRAPI_TOKEN }}
          EOF
          npm ci
          npm run generate

      - name: Push
        working-directory: ./sdi-app/
        run: aws s3 cp ./.output/public s3://tp-sdi/ --recursive

      - name: Clear Cloudfront Cache
        run: aws cloudfront create-invalidation --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} --paths '/*'
